package aoc2021;

import java.util.Locale;

public class aoc2021_0201
{
  public static int navigate(String[] directions)
  {
    int hor = 0;
    int depth = 0;
    int aim = 0;

    for (String direction : directions)
    {
      String[] parts = direction.split(" ");
      int num = Integer.valueOf(parts[1]);
      String dir = parts[0].toLowerCase(Locale.ROOT);
      if (dir.equals("forward"))
      {
        hor += num;
        depth += aim * num;
      }
      else if (dir.equals("up"))
      {
        aim -= num;
      }
      else if (dir.equals("down"))
      {
        aim += num;
      }
      else
      {
        System.out.println("Unknown direction: '" + dir +"', num=" + num + ": " + direction);
      }
    }
    return hor * depth;
  }


  public static int oldNavigate(String[] directions)
  {
    int hor = 0;
    int depth = 0;

    for (String direction : directions)
    {
      String[] parts = direction.split(" ");
      int num = Integer.valueOf(parts[1]);
      String dir = parts[0].toLowerCase(Locale.ROOT);
      if (dir.equals("forward"))
      {
        hor += num;
      }
      else if (dir.equals("up"))
      {
        depth -= num;
      }
      else if (dir.equals("down"))
      {
        depth += num;
      }
      else
      {
        System.out.println("Unknown direction: '" + dir +"', num=" + num + ": " + direction);
      }
    }
    return hor * depth;
  }

  public static void main(String[] args)
  {
    String values = "forward 5\n" +
        "forward 1\n" +
        "forward 3\n" +
        "down 8\n" +
        "up 6\n" +
        "down 5\n" +
        "forward 6\n" +
        "down 9\n" +
        "down 7\n" +
        "up 9\n" +
        "down 9\n" +
        "forward 5\n" +
        "forward 3\n" +
        "down 3\n" +
        "forward 1\n" +
        "forward 8\n" +
        "down 8\n" +
        "forward 6\n" +
        "forward 9\n" +
        "forward 5\n" +
        "down 8\n" +
        "up 1\n" +
        "forward 4\n" +
        "forward 8\n" +
        "down 4\n" +
        "forward 2\n" +
        "down 1\n" +
        "up 8\n" +
        "up 9\n" +
        "down 4\n" +
        "forward 5\n" +
        "up 9\n" +
        "forward 1\n" +
        "down 9\n" +
        "down 7\n" +
        "down 4\n" +
        "down 6\n" +
        "down 3\n" +
        "forward 5\n" +
        "up 4\n" +
        "up 7\n" +
        "forward 1\n" +
        "down 1\n" +
        "up 3\n" +
        "forward 8\n" +
        "down 8\n" +
        "up 2\n" +
        "forward 2\n" +
        "down 7\n" +
        "down 7\n" +
        "down 4\n" +
        "forward 3\n" +
        "down 5\n" +
        "up 8\n" +
        "down 6\n" +
        "up 2\n" +
        "down 7\n" +
        "forward 8\n" +
        "down 7\n" +
        "down 7\n" +
        "up 6\n" +
        "forward 8\n" +
        "up 1\n" +
        "down 4\n" +
        "forward 1\n" +
        "down 1\n" +
        "down 9\n" +
        "down 1\n" +
        "down 7\n" +
        "forward 2\n" +
        "forward 3\n" +
        "up 8\n" +
        "up 1\n" +
        "forward 4\n" +
        "forward 7\n" +
        "forward 9\n" +
        "up 8\n" +
        "down 9\n" +
        "down 3\n" +
        "down 5\n" +
        "down 5\n" +
        "forward 7\n" +
        "forward 3\n" +
        "up 7\n" +
        "forward 6\n" +
        "up 6\n" +
        "forward 3\n" +
        "down 2\n" +
        "down 5\n" +
        "down 2\n" +
        "up 6\n" +
        "down 5\n" +
        "down 5\n" +
        "forward 7\n" +
        "forward 2\n" +
        "forward 7\n" +
        "down 6\n" +
        "forward 1\n" +
        "forward 8\n" +
        "up 6\n" +
        "forward 2\n" +
        "down 5\n" +
        "forward 3\n" +
        "up 2\n" +
        "forward 3\n" +
        "down 2\n" +
        "forward 4\n" +
        "forward 6\n" +
        "down 8\n" +
        "forward 7\n" +
        "forward 6\n" +
        "down 1\n" +
        "down 8\n" +
        "forward 7\n" +
        "up 2\n" +
        "forward 2\n" +
        "down 7\n" +
        "up 6\n" +
        "forward 7\n" +
        "down 9\n" +
        "down 7\n" +
        "forward 4\n" +
        "down 9\n" +
        "down 4\n" +
        "forward 6\n" +
        "up 6\n" +
        "up 5\n" +
        "down 5\n" +
        "up 7\n" +
        "forward 6\n" +
        "down 1\n" +
        "down 5\n" +
        "forward 1\n" +
        "up 6\n" +
        "forward 1\n" +
        "down 7\n" +
        "forward 7\n" +
        "forward 4\n" +
        "up 5\n" +
        "down 3\n" +
        "forward 7\n" +
        "forward 6\n" +
        "up 9\n" +
        "forward 8\n" +
        "forward 1\n" +
        "up 2\n" +
        "up 8\n" +
        "forward 7\n" +
        "up 7\n" +
        "down 1\n" +
        "forward 9\n" +
        "down 5\n" +
        "forward 5\n" +
        "forward 2\n" +
        "forward 2\n" +
        "forward 6\n" +
        "up 5\n" +
        "up 1\n" +
        "forward 6\n" +
        "up 3\n" +
        "down 7\n" +
        "down 6\n" +
        "down 1\n" +
        "forward 1\n" +
        "forward 8\n" +
        "forward 8\n" +
        "down 8\n" +
        "up 3\n" +
        "down 7\n" +
        "down 2\n" +
        "down 9\n" +
        "forward 9\n" +
        "down 7\n" +
        "forward 4\n" +
        "down 9\n" +
        "forward 8\n" +
        "down 1\n" +
        "down 5\n" +
        "down 9\n" +
        "down 8\n" +
        "forward 8\n" +
        "down 3\n" +
        "forward 4\n" +
        "forward 6\n" +
        "up 3\n" +
        "forward 4\n" +
        "down 9\n" +
        "down 6\n" +
        "up 6\n" +
        "up 3\n" +
        "down 2\n" +
        "up 1\n" +
        "forward 5\n" +
        "down 7\n" +
        "down 3\n" +
        "forward 5\n" +
        "up 1\n" +
        "forward 2\n" +
        "down 3\n" +
        "down 3\n" +
        "forward 6\n" +
        "down 5\n" +
        "down 7\n" +
        "down 1\n" +
        "down 2\n" +
        "down 7\n" +
        "forward 4\n" +
        "forward 7\n" +
        "down 7\n" +
        "forward 6\n" +
        "forward 2\n" +
        "down 1\n" +
        "down 8\n" +
        "forward 5\n" +
        "forward 5\n" +
        "down 7\n" +
        "forward 6\n" +
        "forward 7\n" +
        "up 2\n" +
        "forward 5\n" +
        "down 8\n" +
        "forward 7\n" +
        "down 7\n" +
        "up 6\n" +
        "forward 6\n" +
        "down 2\n" +
        "down 7\n" +
        "forward 6\n" +
        "forward 4\n" +
        "down 5\n" +
        "down 7\n" +
        "forward 2\n" +
        "forward 6\n" +
        "forward 6\n" +
        "down 7\n" +
        "down 9\n" +
        "forward 9\n" +
        "forward 4\n" +
        "up 9\n" +
        "up 2\n" +
        "up 2\n" +
        "forward 4\n" +
        "down 6\n" +
        "forward 7\n" +
        "up 5\n" +
        "forward 1\n" +
        "forward 6\n" +
        "down 8\n" +
        "forward 2\n" +
        "down 8\n" +
        "forward 9\n" +
        "forward 5\n" +
        "forward 1\n" +
        "up 8\n" +
        "down 4\n" +
        "down 2\n" +
        "down 9\n" +
        "up 6\n" +
        "forward 8\n" +
        "down 9\n" +
        "forward 3\n" +
        "down 3\n" +
        "down 9\n" +
        "down 9\n" +
        "down 6\n" +
        "forward 7\n" +
        "down 4\n" +
        "forward 8\n" +
        "down 7\n" +
        "down 8\n" +
        "up 4\n" +
        "up 3\n" +
        "forward 1\n" +
        "up 9\n" +
        "up 1\n" +
        "up 9\n" +
        "up 7\n" +
        "down 1\n" +
        "forward 5\n" +
        "forward 7\n" +
        "forward 3\n" +
        "forward 8\n" +
        "up 4\n" +
        "forward 7\n" +
        "down 5\n" +
        "forward 9\n" +
        "up 3\n" +
        "up 3\n" +
        "down 2\n" +
        "forward 3\n" +
        "up 3\n" +
        "down 3\n" +
        "down 4\n" +
        "up 6\n" +
        "down 7\n" +
        "down 1\n" +
        "down 7\n" +
        "forward 1\n" +
        "down 4\n" +
        "forward 9\n" +
        "down 9\n" +
        "up 8\n" +
        "up 5\n" +
        "down 7\n" +
        "up 1\n" +
        "forward 6\n" +
        "down 1\n" +
        "down 4\n" +
        "down 3\n" +
        "forward 7\n" +
        "forward 4\n" +
        "up 6\n" +
        "down 2\n" +
        "down 1\n" +
        "forward 1\n" +
        "up 5\n" +
        "down 2\n" +
        "down 9\n" +
        "up 2\n" +
        "up 3\n" +
        "forward 5\n" +
        "forward 5\n" +
        "down 8\n" +
        "down 4\n" +
        "up 4\n" +
        "down 1\n" +
        "forward 8\n" +
        "up 7\n" +
        "down 1\n" +
        "down 4\n" +
        "forward 3\n" +
        "up 4\n" +
        "down 4\n" +
        "down 5\n" +
        "down 9\n" +
        "down 1\n" +
        "down 7\n" +
        "up 2\n" +
        "down 6\n" +
        "up 9\n" +
        "down 3\n" +
        "down 1\n" +
        "down 8\n" +
        "down 4\n" +
        "up 2\n" +
        "forward 6\n" +
        "forward 9\n" +
        "down 6\n" +
        "forward 6\n" +
        "forward 4\n" +
        "forward 8\n" +
        "forward 5\n" +
        "forward 6\n" +
        "forward 9\n" +
        "down 3\n" +
        "forward 8\n" +
        "forward 6\n" +
        "forward 7\n" +
        "up 9\n" +
        "forward 3\n" +
        "up 3\n" +
        "forward 5\n" +
        "down 5\n" +
        "up 9\n" +
        "forward 1\n" +
        "forward 9\n" +
        "down 7\n" +
        "forward 5\n" +
        "forward 5\n" +
        "forward 6\n" +
        "forward 5\n" +
        "forward 9\n" +
        "forward 8\n" +
        "forward 3\n" +
        "down 2\n" +
        "forward 6\n" +
        "forward 8\n" +
        "down 4\n" +
        "forward 4\n" +
        "forward 1\n" +
        "forward 1\n" +
        "down 2\n" +
        "forward 2\n" +
        "forward 5\n" +
        "up 4\n" +
        "forward 3\n" +
        "down 3\n" +
        "down 5\n" +
        "down 6\n" +
        "forward 4\n" +
        "down 8\n" +
        "down 4\n" +
        "forward 5\n" +
        "down 7\n" +
        "up 3\n" +
        "up 6\n" +
        "forward 3\n" +
        "forward 2\n" +
        "forward 5\n" +
        "down 9\n" +
        "down 4\n" +
        "down 8\n" +
        "down 2\n" +
        "forward 4\n" +
        "forward 7\n" +
        "down 4\n" +
        "up 5\n" +
        "forward 8\n" +
        "down 8\n" +
        "down 1\n" +
        "forward 5\n" +
        "down 6\n" +
        "down 9\n" +
        "up 6\n" +
        "forward 9\n" +
        "down 3\n" +
        "forward 6\n" +
        "forward 2\n" +
        "down 5\n" +
        "forward 1\n" +
        "down 1\n" +
        "down 1\n" +
        "forward 2\n" +
        "up 9\n" +
        "down 1\n" +
        "up 8\n" +
        "forward 9\n" +
        "up 8\n" +
        "forward 2\n" +
        "forward 8\n" +
        "up 2\n" +
        "forward 4\n" +
        "down 5\n" +
        "forward 8\n" +
        "up 2\n" +
        "up 1\n" +
        "forward 4\n" +
        "up 4\n" +
        "up 3\n" +
        "up 5\n" +
        "down 1\n" +
        "forward 3\n" +
        "forward 6\n" +
        "forward 9\n" +
        "forward 6\n" +
        "up 8\n" +
        "forward 2\n" +
        "forward 1\n" +
        "down 2\n" +
        "down 3\n" +
        "down 2\n" +
        "up 4\n" +
        "forward 5\n" +
        "up 2\n" +
        "forward 3\n" +
        "forward 9\n" +
        "up 5\n" +
        "forward 1\n" +
        "down 7\n" +
        "forward 9\n" +
        "down 5\n" +
        "up 7\n" +
        "down 6\n" +
        "forward 7\n" +
        "forward 9\n" +
        "up 6\n" +
        "forward 3\n" +
        "down 1\n" +
        "forward 1\n" +
        "down 8\n" +
        "down 2\n" +
        "up 9\n" +
        "down 4\n" +
        "down 4\n" +
        "down 7\n" +
        "forward 4\n" +
        "forward 1\n" +
        "forward 6\n" +
        "down 9\n" +
        "down 9\n" +
        "down 9\n" +
        "forward 1\n" +
        "forward 6\n" +
        "forward 3\n" +
        "forward 7\n" +
        "forward 3\n" +
        "forward 9\n" +
        "up 8\n" +
        "forward 5\n" +
        "down 1\n" +
        "down 6\n" +
        "up 8\n" +
        "forward 3\n" +
        "up 8\n" +
        "down 6\n" +
        "forward 6\n" +
        "up 2\n" +
        "up 8\n" +
        "up 5\n" +
        "forward 9\n" +
        "down 4\n" +
        "up 1\n" +
        "up 3\n" +
        "up 2\n" +
        "down 9\n" +
        "down 1\n" +
        "forward 7\n" +
        "down 2\n" +
        "forward 6\n" +
        "up 4\n" +
        "down 7\n" +
        "forward 1\n" +
        "down 3\n" +
        "down 5\n" +
        "forward 1\n" +
        "down 3\n" +
        "down 1\n" +
        "forward 8\n" +
        "up 5\n" +
        "forward 5\n" +
        "forward 8\n" +
        "forward 8\n" +
        "forward 8\n" +
        "forward 2\n" +
        "down 3\n" +
        "down 6\n" +
        "up 2\n" +
        "up 2\n" +
        "down 1\n" +
        "up 7\n" +
        "down 9\n" +
        "up 1\n" +
        "up 4\n" +
        "forward 1\n" +
        "forward 4\n" +
        "up 4\n" +
        "up 6\n" +
        "forward 5\n" +
        "forward 2\n" +
        "forward 7\n" +
        "up 8\n" +
        "up 3\n" +
        "down 5\n" +
        "down 9\n" +
        "forward 4\n" +
        "forward 5\n" +
        "forward 5\n" +
        "down 1\n" +
        "up 8\n" +
        "up 2\n" +
        "forward 3\n" +
        "up 2\n" +
        "forward 8\n" +
        "up 2\n" +
        "down 6\n" +
        "up 7\n" +
        "forward 6\n" +
        "down 3\n" +
        "forward 3\n" +
        "down 6\n" +
        "forward 6\n" +
        "forward 4\n" +
        "forward 8\n" +
        "down 8\n" +
        "up 7\n" +
        "down 7\n" +
        "down 2\n" +
        "up 5\n" +
        "up 2\n" +
        "down 4\n" +
        "forward 5\n" +
        "down 3\n" +
        "up 4\n" +
        "down 2\n" +
        "up 2\n" +
        "down 7\n" +
        "forward 4\n" +
        "forward 3\n" +
        "forward 6\n" +
        "down 2\n" +
        "down 8\n" +
        "forward 3\n" +
        "forward 4\n" +
        "forward 4\n" +
        "down 4\n" +
        "down 3\n" +
        "up 6\n" +
        "down 2\n" +
        "forward 7\n" +
        "forward 4\n" +
        "down 7\n" +
        "forward 1\n" +
        "up 6\n" +
        "forward 3\n" +
        "up 3\n" +
        "up 7\n" +
        "forward 6\n" +
        "down 9\n" +
        "down 8\n" +
        "down 3\n" +
        "forward 8\n" +
        "forward 1\n" +
        "up 3\n" +
        "down 5\n" +
        "down 3\n" +
        "forward 1\n" +
        "up 9\n" +
        "down 6\n" +
        "forward 3\n" +
        "down 9\n" +
        "up 7\n" +
        "forward 5\n" +
        "forward 4\n" +
        "forward 7\n" +
        "up 3\n" +
        "forward 3\n" +
        "down 5\n" +
        "forward 7\n" +
        "forward 9\n" +
        "down 6\n" +
        "forward 7\n" +
        "forward 5\n" +
        "up 6\n" +
        "forward 3\n" +
        "forward 3\n" +
        "down 7\n" +
        "forward 4\n" +
        "up 2\n" +
        "forward 8\n" +
        "down 7\n" +
        "up 7\n" +
        "down 7\n" +
        "forward 6\n" +
        "up 3\n" +
        "forward 2\n" +
        "up 7\n" +
        "down 3\n" +
        "down 4\n" +
        "down 1\n" +
        "forward 3\n" +
        "forward 5\n" +
        "up 7\n" +
        "forward 3\n" +
        "down 1\n" +
        "down 2\n" +
        "up 4\n" +
        "forward 2\n" +
        "up 5\n" +
        "down 4\n" +
        "forward 1\n" +
        "down 6\n" +
        "up 1\n" +
        "forward 5\n" +
        "forward 1\n" +
        "down 8\n" +
        "forward 7\n" +
        "down 7\n" +
        "forward 4\n" +
        "forward 7\n" +
        "forward 3\n" +
        "forward 2\n" +
        "forward 1\n" +
        "forward 7\n" +
        "down 1\n" +
        "forward 9\n" +
        "forward 9\n" +
        "forward 8\n" +
        "forward 9\n" +
        "forward 8\n" +
        "forward 5\n" +
        "forward 1\n" +
        "up 5\n" +
        "forward 3\n" +
        "forward 6\n" +
        "forward 1\n" +
        "up 4\n" +
        "down 1\n" +
        "down 9\n" +
        "down 6\n" +
        "forward 4\n" +
        "up 9\n" +
        "down 3\n" +
        "forward 2\n" +
        "down 3\n" +
        "up 2\n" +
        "forward 4\n" +
        "forward 4\n" +
        "down 7\n" +
        "forward 9\n" +
        "forward 3\n" +
        "down 4\n" +
        "up 4\n" +
        "down 4\n" +
        "forward 7\n" +
        "forward 3\n" +
        "forward 6\n" +
        "forward 9\n" +
        "down 4\n" +
        "down 5\n" +
        "down 2\n" +
        "forward 4\n" +
        "up 6\n" +
        "forward 8\n" +
        "forward 3\n" +
        "down 2\n" +
        "down 5\n" +
        "forward 4\n" +
        "down 8\n" +
        "up 5\n" +
        "down 3\n" +
        "forward 6\n" +
        "down 8\n" +
        "up 9\n" +
        "forward 3\n" +
        "forward 8\n" +
        "forward 6\n" +
        "forward 7\n" +
        "down 3\n" +
        "up 6\n" +
        "down 7\n" +
        "down 4\n" +
        "forward 2\n" +
        "forward 5\n" +
        "down 1\n" +
        "down 5\n" +
        "down 5\n" +
        "forward 6\n" +
        "forward 6\n" +
        "down 1\n" +
        "forward 2\n" +
        "up 1\n" +
        "down 2\n" +
        "down 3\n" +
        "forward 3\n" +
        "forward 9\n" +
        "down 9\n" +
        "down 1\n" +
        "up 8\n" +
        "down 5\n" +
        "down 2\n" +
        "up 7\n" +
        "forward 8\n" +
        "up 7\n" +
        "forward 3\n" +
        "forward 6\n" +
        "down 2\n" +
        "down 3\n" +
        "forward 1\n" +
        "down 6\n" +
        "down 1\n" +
        "forward 4\n" +
        "up 2\n" +
        "down 3\n" +
        "up 7\n" +
        "down 3\n" +
        "down 2\n" +
        "up 8\n" +
        "up 7\n" +
        "down 3\n" +
        "forward 4\n" +
        "down 8\n" +
        "up 2\n" +
        "down 6\n" +
        "forward 9\n" +
        "down 1\n" +
        "up 3\n" +
        "up 1\n" +
        "down 4\n" +
        "up 6\n" +
        "down 2\n" +
        "forward 1\n" +
        "down 6\n" +
        "forward 4\n" +
        "forward 3\n" +
        "down 7\n" +
        "down 2\n" +
        "down 6\n" +
        "down 2\n" +
        "down 7\n" +
        "forward 2\n" +
        "down 1\n" +
        "up 8\n" +
        "up 6\n" +
        "up 1\n" +
        "forward 5\n" +
        "down 9\n" +
        "down 5\n" +
        "up 7\n" +
        "down 4\n" +
        "forward 4\n" +
        "forward 5\n" +
        "up 5\n" +
        "forward 6\n" +
        "forward 1\n" +
        "forward 5\n" +
        "forward 1\n" +
        "forward 6\n" +
        "down 6\n" +
        "forward 3\n" +
        "up 4\n" +
        "forward 6\n" +
        "down 6\n" +
        "forward 1\n" +
        "forward 5\n" +
        "forward 8\n" +
        "down 3\n" +
        "forward 6\n" +
        "forward 1\n" +
        "up 1\n" +
        "up 7\n" +
        "forward 7\n" +
        "forward 8\n" +
        "up 6\n" +
        "forward 9\n" +
        "up 5\n" +
        "forward 1\n" +
        "forward 5\n" +
        "down 3\n" +
        "up 3\n" +
        "up 9\n" +
        "forward 9\n" +
        "forward 5\n" +
        "forward 3\n" +
        "forward 2\n" +
        "forward 4\n" +
        "down 6\n" +
        "up 5\n" +
        "down 2\n" +
        "forward 5\n" +
        "down 2\n" +
        "down 5\n" +
        "down 6\n" +
        "forward 7\n" +
        "down 2\n" +
        "forward 7\n" +
        "forward 2\n" +
        "forward 8\n" +
        "up 1\n" +
        "forward 9\n" +
        "down 2\n" +
        "up 1\n" +
        "down 9\n" +
        "forward 8\n" +
        "forward 3\n" +
        "up 9\n" +
        "down 1\n" +
        "down 1\n" +
        "down 8\n" +
        "up 4\n" +
        "up 9\n" +
        "forward 9\n" +
        "forward 3\n" +
        "down 9\n" +
        "forward 3\n" +
        "forward 4\n" +
        "down 8\n" +
        "forward 8\n" +
        "forward 7\n" +
        "down 9\n" +
        "up 2\n" +
        "down 9\n" +
        "down 8\n" +
        "down 9\n" +
        "forward 4\n" +
        "up 6\n" +
        "down 4\n" +
        "forward 8\n" +
        "forward 5\n" +
        "up 2\n" +
        "forward 5\n" +
        "down 3\n" +
        "forward 6\n" +
        "down 5\n" +
        "forward 8\n" +
        "up 3\n" +
        "down 5\n" +
        "down 4\n" +
        "forward 5\n" +
        "up 3\n" +
        "up 8\n" +
        "forward 1\n" +
        "up 8\n" +
        "forward 4\n" +
        "down 4\n" +
        "forward 7\n" +
        "forward 5\n" +
        "forward 7\n" +
        "forward 9\n" +
        "up 1\n" +
        "down 6\n" +
        "forward 8\n" +
        "up 1\n" +
        "down 5\n" +
        "up 6\n" +
        "down 9\n" +
        "down 5\n" +
        "forward 3\n" +
        "up 1\n" +
        "forward 4\n" +
        "up 4\n" +
        "down 4\n" +
        "forward 5\n" +
        "forward 8\n" +
        "down 2\n" +
        "up 7\n" +
        "down 6\n" +
        "forward 7\n" +
        "up 7\n" +
        "forward 5\n" +
        "down 2\n" +
        "forward 9\n" +
        "forward 1\n" +
        "down 9\n" +
        "down 8\n" +
        "forward 7\n" +
        "forward 7\n" +
        "forward 1\n" +
        "up 3\n" +
        "up 1\n" +
        "forward 2\n" +
        "down 2\n" +
        "up 9\n" +
        "down 2\n" +
        "forward 7\n" +
        "down 1\n" +
        "down 5\n" +
        "down 4\n" +
        "up 7\n" +
        "forward 1\n" +
        "down 3\n" +
        "forward 9\n" +
        "down 6\n" +
        "forward 4\n" +
        "down 4\n" +
        "down 9\n" +
        "down 3\n" +
        "up 3\n" +
        "down 3\n" +
        "up 8\n" +
        "down 2\n" +
        "forward 1\n" +
        "forward 5\n" +
        "forward 5\n" +
        "down 2\n" +
        "forward 7\n" +
        "down 7\n" +
        "down 6\n" +
        "forward 6\n" +
        "up 5\n" +
        "down 4\n" +
        "down 8\n" +
        "down 7\n" +
        "forward 7\n" +
        "up 3\n" +
        "down 3\n" +
        "down 3\n" +
        "forward 8\n" +
        "forward 5\n" +
        "down 1\n" +
        "up 6\n" +
        "down 3\n" +
        "up 2\n" +
        "down 6\n" +
        "up 7\n" +
        "down 4\n" +
        "up 2\n" +
        "forward 4\n" +
        "forward 9\n" +
        "forward 9\n" +
        "up 1\n" +
        "forward 7\n" +
        "up 7\n" +
        "forward 7\n" +
        "forward 6\n" +
        "forward 3\n" +
        "forward 1\n" +
        "down 5\n" +
        "down 3\n" +
        "forward 4\n" +
        "up 9\n" +
        "down 5\n" +
        "up 2\n" +
        "down 6\n" +
        "down 5\n" +
        "forward 6\n" +
        "forward 4\n" +
        "up 7\n" +
        "up 6\n" +
        "down 9\n" +
        "forward 4\n" +
        "up 1\n" +
        "up 6\n" +
        "up 3\n" +
        "forward 9\n" +
        "forward 3\n" +
        "forward 9\n" +
        "down 7\n" +
        "forward 6\n" +
        "down 6\n" +
        "forward 8";
//    System.out.println(oldNavigate(values.split("\n")));
    System.out.println(navigate(values.split("\n")));
  }
}
